### ISSUE TITLE
Pymode compatibility with flake8-vim

### ISSUE THREAD

**Issue by milin** [andviro/flake8-vim#20]
If one is currently using python-mode with vim (7.4) and they have the following in their vimrc

```
let g:pymode_rope = 1
let g:pymode_lint = 1
```

They get the following error with flake8-vim,
```
Error detected while processing function pymode#buffer_post_write:
line    2:
E121: Undefined variable: b:pymode_modified
E15: Invalid expression: b:pymode_modified && g:pymode_rope_regenerate_on_write
line    8:
E121: Undefined variable: b:pymode_modified
E15: Invalid expression: g:pymode_lint_unmodified || (g:pymode_lint_on_write && b:pymode_modified)
```

One way to resolve the issue is to do,

```
let g:pymode_rope = 0
let g:pymode_lint = 0
```

**Comment by andviro** [comment]
Hello. Flake8-vim was originally intended as a replacement for pymode, and it's better suited to work together with jedi-vim for code navigation and refactoring. I can only recommend you to ditch python rope altogether, jedi is better IMO anyway.
