### ISSUE TITLE
g:PyFlakeMaxLineLength is ignored

### ISSUE THREAD

**Issue by collinanderson** [andviro/flake8-vim#7]
I just searched the code and don't see it being used anywhere. I would use it if it worked.

**Comment by avg-I** [comment]
Has this issue been fixed?

**Comment by andviro** [comment]
sorry friends, I've been busy lately. I'll try to find some time for this, but don't hold your breath. It'd be the best if someone will offer PR for this.

**Comment by mbudnek** [comment]
I just created PR #25 that fixes this issue.

**Comment by andviro** [comment]
Thanks, @mbudnek!
